package domain.request;

public enum RequestCode {
    GET_ALL_RECORDS, GET_RECORDS_BY_GROUP, UPDATE_RECORD, ADD_RECORD, DELETE_RECORD, ADD_ACCOUNT, UPDATE_ACCOUNT,
    DOES_ACCOUNT_EXIST, LOGIN, UPDATE_ACCOUNT_STORAGE, UPDATE_RECORD_STORAGE
}
